sl/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^stack/', include('stack.urls', namespace='stack', app_name='stack')),
    url(r'^$', TemplateView.as_view(template_name='index.html')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stack/urls.py
from django.conf.urls import patterns, url, include
from stack.views import StackListView, StackUpdate, StackCreate, StackDelete, StackDetailView
from django.contrib.auth.decorators import login_required

from tastypie.api import Api
from stack.api import AppResource, AppStackResource, StackResource, ReferenceResource, ArchitectureResource, SystemResource, CategoryResource

v1_api = Api(api_name='v1')
v1_api.register(AppResource())
v1_api.register(AppStackResource())
v1_api.register(StackResource())
v1_api.register(ReferenceResource())
v1_api.register(ArchitectureResource())
v1_api.register(SystemResource())
v1_api.register(CategoryResource())


urlpatterns = patterns('',
    (r'^api/', include(v1_api.urls)),
    url(r'^delete/(?P<slug>[-_\w]+)/$', login_required(StackDelete.as_view()),
        name='stack-delete'),
    url(r'^edit/(?P<slug>[-_\w]+)/$', login_required(StackUpdate.as_view()),
        name='stack-update'),
    url(r'^add/$', login_required(StackCreate.as_view()),
        name='stack-create'),
    url(r'^view/(?P<slug>[-_\w]+)/$', StackDetailView.as_view(),
        name='stack-detail'),
    url(r'^$', StackListView.as_view(), name='stack-list'),
)

accounts/models.py
from django.db import models

ref/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic

class Reference(models.Model):
    url = models.URLField()
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = generic.GenericForeignKey('content_type', 'object_id')

    def __unicode__(self):
        return self.url

stack/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors.resize import ResizeToFit
from django.contrib.contenttypes import generic
from ref.models import Reference

class Architecture(models.Model):
    app = models.ForeignKey('App')
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    references = generic.GenericRelation(Reference)

class App(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField(blank=True)
    logo = ProcessedImageField(processors=[ResizeToFit(200,200)],
            upload_to='logo', null=True, blank=True,
            format='JPEG', options={'quality':90})
    slug = models.SlugField(unique=True)
    official_site = models.URLField(null=True, blank=True)
    stacks = models.ManyToManyField('self', through='AppStack',
            symmetrical=False, blank=True)

    categories = models.ManyToManyField('Category')

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('stack:stack-detail', [self.slug])

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return self.name

class AppStack(models.Model):
    app = models.ForeignKey('App', related_name="app_stacks")
    stack = models.ForeignKey('App', related_name="stack_set")
    description = models.TextField(blank=True)
    used_since = models.DateField(blank=True, null=True)
    used_until = models.DateField(blank=True, null=True)
    references = generic.GenericRelation(Reference)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "%(app)s - %(stack)s" % \
                {'app':self.app,
                'stack':self.stack}

stack/forms.py
from django import forms
from stack.models import App

class AppForm(forms.ModelForm):
    class Meta:
        model = App
        exclude = ('stacks', )

stack/views.py
import json
from django.http import HttpResponse
from stack.models import App, AppStack, Architecture
from stack.forms import AppForm
from django.views.generic.detail import SingleObjectMixin, SingleObjectTemplateResponseMixin, BaseDetailView
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, CreateView, DeleteView

class JSONResponseMixin(object):
    """
    A mixin that can be used to render a JSON response.
    """
    response_class = HttpResponse

    def render_to_response(self, context, **response_kwargs):
        """
        Returns a JSON response, transforming 'context' to make the payload.
        """
        response_kwargs['content_type'] = 'application/json'
        return self.response_class(
            self.convert_context_to_json(context),
            **response_kwargs
        )

    def convert_context_to_json(self, context):
        "Convert the context dictionary into a JSON object"
        # Note: This is *EXTREMELY* naive; in reality, you'll need
        # to do much more complex handling to ensure that arbitrary
        # objects -- such as Django model instances or querysets
        # -- can be serialized as JSON.
        return json.dumps(context)

class StackListView(ListView):
    model = App

    def get_context_data(self, **kwargs):
        context = super(StackListView, self).get_context_data(**kwargs)
        context["app_meta"] = App._meta
        return context


class StackDetailView(DetailView):
    model = App

class StackCreate(CreateView):
    model = App
    form_class = AppForm

    def get_context_data(self, **kwargs):
        context = super(StackCreate, self).get_context_data(**kwargs)
        context["app_stack_meta"] = AppStack._meta
        context["architecture_meta"] = Architecture._meta
        return context

class StackUpdate(UpdateView):
    model = App
    form_class = AppForm

    def get_context_data(self, **kwargs):
        context = super(StackUpdate, self).get_context_data(**kwargs)
        context["app_stack_meta"] = AppStack._meta
        context["architecture_meta"] = Architecture._meta
        return context

class StackDelete(DeleteView):
    model = App

sl/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        {% block meta %}{% endblock %}

        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <style>
            body {
                padding-top: 60px;
                padding-bottom: 40px;
            }
        </style>
        <link rel="stylesheet" href="{% static 'css/bootstrap-responsive.min.css' %}">
        <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/themes/base/jquery-ui.css">
        {% block style %}
        {% endblock %}

        <script src="{% static 'js/vendor/modernizr-2.6.2-respond-1.1.0.min.js' %}"></script>
        {% block extra_head %}
        {% endblock %}
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

        <!-- This code is taken from http://twitter.github.com/bootstrap/examples/hero.html -->

        {% block body %}
        {% endblock %}

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="{% static 'js/vendor/jquery-1.8.3.min.js' %}"><\/script>')</script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>

        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>

        {% block script %}
        {% endblock %}

        <script>
          var _gaq=[['_setAccount','UA-37352165-1'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
        {% block extra_body %}{% endblock %}
    </body>
</html>

sl/templates/index.html
{% extends "base.html" %}

{% load staticfiles %}

{% block style %}
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="stylesheet" href="http://angular-ui.github.com/angular-ui/build/angular-ui.css">
{% endblock %}

{% block script %}
  <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.0.3/angular.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.0.3/angular-resource.js"></script>
  <script src="http://angular-ui.github.com/angular-ui/build/angular-ui.js"></script>
  <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-modal.js"></script>
  <script src="{% static 'js/app.js' %}"></script>
  <script src="{% static 'js/controllers.js' %}"></script>
{% endblock %}

{% block body %}
        <div ng-app="slApp" ng-controller="SystemListCtrl">
            <div class="navbar navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <a class="brand" href="#">StackLegacy</a>
                        <div class="nav-collapse collapse">
                            <ul class="nav">
                              <li class="dropdown">
                                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse <b class="caret"></b></a>
                                  <ul class="dropdown-menu">
                                    <li><a href="/#/latest">Latest System</a></li>
                                    <li><a href="/#/recent">Recently Updated</a></li>
                                  </ul>
                              </li>
                              <li>
                                <a href="http://blog.stacklegacy.com">Blog</a>
                              </li>
                            </ul>
                            <form class="navbar-search pull-right">
                                <input class="search-query" type="text" placeholder="Search" ng-model="query" ng-change="doSearch()">
                            </form>
                        </div><!--/.nav-collapse -->

                    </div>
                </div>
            </div>

            <div class="container">

                <div ng-view class="clearfix"></div>

                <hr>

                <footer>
                    <p>&copy; StackLegacy 2013</p>
                </footer>

            </div> <!-- /container -->
        </div>
{% endblock %}

sl/templates/stack/app_confirm_delete.html
{% extends "stack/base.html" %}

{% block content %}

{% endblock %}

sl/templates/stack/app_detail.html
{% extends "stack/base.html" %}

{% block content %}
<h2>{{ object.name }}</h2>
{% endblock %}

sl/templates/stack/app_form.html
{% extends "stack/base.html" %}
{% load admin_urls %}

{% block content %}
<div class='row'>
  <section class='tabbable tabs-left span8'>
    <ul class="nav nav-tabs">
      <li class="active">
        <a href="#system" data-toggle="tab">System</a>
      </li>
      <li>
        <a href="#architectures" data-toggle="tab">Architectures</a>
      </li>
      <li>
        <a href="#stacks" data-toggle="tab">Stacks</a>
      </li>
    </ul>
    <div class="tab-content span5">
      <section class="tab-pane active" id="system">
        <form action='' method='POST' class='form-horizontal'>
            {% csrf_token %}
            <legend>System Detail</legend>
            {% if form.errors %}
            <div class="alert alert-error">
              <button type="button" class="close" data-dismiss="alert">×</button> 
              <strong>Fail: </strong>Please Correct your input below!!
              {{ form.errors }}
            </div>
            {% endif %}
            <div class='control-group {% if form.name.errors %}error{% endif %}'>
              <label for='name' class='control-label'>Name</label>
              <div class='controls'>
                {{ form.name }}
                <span class="help-inline">{{ form.name.errors }}</span>
              </div>
            </div>

            <div class='control-group {% if form.description.errors %}error{% endif %}'>
              <label for='description' class='control-label'>Description</label>
              <div class='controls'>
                {{ form.description }}
                <span class="help-inline">{{ form.description.errors }}</span>
              </div>
            </div>

            <div class='control-group {% if form.logo.errors %}error{% endif %}'>
              <label for='logo' class='control-label'>Logo</label>
              <div class='controls'>
                {{ form.logo }}
                <span class="help-inline">{{ form.logo.errors }}</span>
                <label for="logo-clear" class="checkbox"><input type="checkbox" id="logo-clear" />Clear</label>
              </div>
            </div>

            <div class='control-group {% if form.slug.errors %}error{% endif %}'>
              <label for="slug" class='control-label'>Slug</label>
              <div class='controls'>
                {{ form.slug }}
                <span class="help-inline">{{ form.slug.errors }}</span>
              </div>
            </div>

            <div class='control-group {% if form.official_site.errors %}error{% endif %}'>
              <label for="oficial_site" class='control-label'>Official site</label>
              <div class='controls'>
                {{ form.official_site }}
                <span class="help-inline">{{ form.official_site.errors }}</span>
              </div>

            </div>

            <div class='control-group {% if form.categories.errors %}error{% endif %}'>
              <label for="categories" class='control-label'>Categories</label>
              <div class='controls'>
                {{ form.categories }}
                <span class="help-inline">{{ form.categories.errors }}</span>
              </div>
            </div>

            <div class='control-group'>
              <div class='controls'>
                <button type='submit' class='btn btn-primary' >Submit</button>
              </div>
            </div>
        </form>
      </section>
      <section class="tab-pane" id="architectures">
        <legend>Architectures</legend>
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th>Title</th>
              <th>Description</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for arc in object.architectures.all %}
            <tr>
              <td>{{ arc.title }}</td>
              <td>{{ arc.description }}</td>
              <td>
                <a href='{% url architecture_meta|admin_urlname:'change' arc.id%}' class='btn btn-warning'>Edit</a>
                <a href='{% url architecture_meta|admin_urlname:'delete' arc.id %}' class='btn btn-danger'>Delete</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <a href='{% url architecture_meta|admin_urlname:'add' %}' class='btn btn-danger'>Add Architecture</a>
      </section>
      <section class="tab-pane" id="stacks">
        <legend>Stacks</legend>
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th>Title</th>
              <th>Description</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for app_stack in object.app_stacks.all %}
            <tr>
              <td>{{ app_stack.stack.name }}</td>
              <td>{{ app_stack.description }}</td>
              <td>
                <a href='{% url app_stack_meta|admin_urlname:'change' app_stack.id%}' class='btn btn-warning'>Edit</a>
                <a href='{% url app_stack_meta|admin_urlname:'delete' app_stack.id %}' class='btn btn-danger'>Delete</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <a href='{% url app_stack_meta|admin_urlname:'add' %}' class='btn btn-danger'>Add Stack</a>
      </section>
    </div>
  </section>
</div>
{% endblock %}

sl/templates/stack/app_list.html
{% extends "stack/base.html" %}
{% load admin_urls %}

{% block content %}
<h2>Systems & Stacks</h2>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>System Name</th>
      <th>Short Description</th>
      <th>Stacks</th>
      <th>Architectures</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
  {% for app in object_list %}
    <tr>
      <td>{{ app.id }}</td>
      <td><a href=''>{{ app.name }}</a></td>
      <td>{{ app.description|linebreaks|truncatewords:5 }}</td>
      <td>
        <ul>
        {% for stack in app.stacks.all %}
          <li>{{ stack }}</li>
        {% endfor %}
        </ul>
      </td>
      <td>
        <ul>
        {% for arc in app.architecture_set.all %}
          <li>{{ arc.title }}</li>
        {% endfor %}
        </ul>
      </td>
      <td>
        <a href='{% url "stack:stack-update" app.slug %}' class='btn btn-warning'>Edit</a>
        <a href='{% url app_meta|admin_urlname:'delete' app.id %}' class='btn btn-danger'>Delete</a>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

sl/templates/stack/base.html
{% extends "base.html" %}

{% block script %}
<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.3/underscore-min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/backbone.js/0.9.9/backbone-min.js"></script>
{% endblock %}

{% block body %}
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="/">StackLegacy</a>
                <ul class="nav">
                  <li><a href="/stack">Admin</a></li>
                  <li><a href="/stack/add">Add Stack</a></li>
                </ul>
            </div>
        </div>
    </div>


          <div class="container">

              <div class="clearfix">
                {% block content %}{% endblock %}
              </div>

              <hr>

              <footer>
                  <p>&copy; StackLegacy 2013</p>
              </footer>

          </div> <!-- /container -->
{% endblock %}